[package]
name = "fireworks-erikh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "^0.27"
rand = "^0.8"
lazy_static = "^1"
signal-hook = "^0.3"
